const sampleData = [
  {
    id: '123',
    number: '1',
    first_name: 'John',
    last_name: 'Doe',
    position: 'qb',
    height: '6-4',
    weight: '225',
    age: '26',
    years_pro: '3',
    college: 'Texas',
  },
  {
    id: '456',
    number: '2',
    first_name: 'James',
    last_name: 'Test',
    position: 'cb',
    height: '6-0',
    weight: '190',
    age: '31',
    years_pro: '10',
    college: 'Mississippi State',
  },
  {
    id: '789',
    number: '3',
    first_name: 'Patrick',
    last_name: 'Green',
    position: 'cb',
    height: '6-2',
    weight: '198',
    age: '24',
    years_pro: '2',
    college: 'Alabama',
  },
  {
    id: '987',
    number: '4',
    first_name: 'Raymond',
    last_name: 'Sample',
    position: 'k',
    height: '6-0',
    weight: '175',
    age: '22',
    years_pro: '1',
    college: 'Memphis',
  },
];

export default sampleData;
