service: eagles-api

plugins:
  - ${file(./plugins.js):getPlugins}

provider:
  name: aws
  runtime: nodejs22.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
