name: Update NFL Roster

on:
  schedule:
    - cron: '0 0 1 * *' # 1st of the month at 00:00 UTC

jobs:
  update-roster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update roster script
        run: python -m scripts.update_roster

      - name: Commit updated official_roster.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/official_roster.json
          git commit -m "Update roster for $(date +'%B %Y')" || echo "No changes to commit"
          git push
